### ISSUE TITLE
No icons 

### ISSUE THREAD

**Issue by chchris25** [ONElua/Shortcuts-Enhancer#1]
Installed this and now I have no icons at all, not even the default icons. Even though there are no icons, the shortcuts still work. How do you fix, uninstall, or restore default settings? 
![C59B95B3-FE60-4F2B-9925-4A0B8DCEFE1F](https://user-images.githubusercontent.com/29015859/57963491-dc99da80-78f2-11e9-90f8-faa00a9aa1ab.jpeg)
![03905EB3-A9D0-4D38-B380-19178E86977E](https://user-images.githubusercontent.com/29015859/57963492-dc99da80-78f2-11e9-93ac-e4180d9cbb4d.jpeg)

**Comment by chchris25** [comment]
A fellow YouTuber figured out the issue. The below instruction is a temporary fix until a future update is provided by the developer.

sPiRiTiNeXiLe
“For some reason the app is writing the wrong png file names in ur0:/shell/whats_new/np/whatsnew.xml. Should be SHORTCUT001.png, SHORTCUT002.png and SHORTCUT003.png without the "-extranumbers". If you manually edit those entries in the whatsnew.xml and reboot, should fix problem. Also, after fixing, future changes made in Shortcuts Enhancer seem to work fine.”

**Comment by ONElua** [comment]
Fix in the v2.00
